### ISSUE TITLE
Add support for services

### ISSUE THREAD

**Issue by thosakwe** [angel-dart-archive/demon#3]
```yaml
servers:
  $default:
    server:
      host: 127.0.0.1
      port: 3000
    services:
      "api/todos":
        mongo: "mongodb://localhost:27017/angel"
        collection: todos
```
